"""
representation_viz.py -- t-SNE/UMAP visualization of learned representations (D, E, F).

Loads the latent representations generated by pipeline_d, pipeline_e, pipeline_f
from data/processed/{dataset}/{pipeline}/train.csv and projects them into 2D
using t-SNE (and optionally UMAP) for visual inspection.

Produces:
  results/visualize/repr_tsne_{dataset}_{pipeline}.png
      t-SNE 2D scatter, colored by target class
  results/visualize/repr_umap_{dataset}_{pipeline}.png   (if umap-learn installed)
      UMAP 2D scatter, colored by target class
  results/visualize/repr_comparison_{dataset}.png
      Side-by-side t-SNE for D / E / F

Usage:
  python scripts/visualize/representation_viz.py
  python scripts/visualize/representation_viz.py --dataset bank
  python scripts/visualize/representation_viz.py --pipeline d
  python scripts/visualize/representation_viz.py --method umap
"""
import sys
import argparse
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler

from config import DATA_PROC, RESULTS_DIR, SEED
from scripts.utils import get_logger, ensure_dirs

logger = get_logger("representation_viz")
VIZ_DIR = RESULTS_DIR / "visualize"
ensure_dirs(VIZ_DIR)

AI_PIPELINES = ["d", "e", "f"]
PIPELINE_TITLES = {
    "d": "Pipeline D -- Denoising Autoencoder (DAE)",
    "e": "Pipeline E -- Variational Autoencoder (VAE)",
    "f": "Pipeline F -- FT-Transformer",
}
CLASS_COLORS = {0: "#90CAF9", 1: "#E53935"}
CLASS_LABELS = {0: "Negative (majority)", 1: "Positive (minority)"}


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_latent(dataset: str, pipeline: str,
                max_samples: int = 5000) -> tuple:
    """
    Load latent representations from train.csv.

    Returns (X_latent, y) where X_latent is already in latent space.
    Subsamples if dataset is large to keep t-SNE runtime manageable.
    """
    csv_path = DATA_PROC / dataset / pipeline / "train.csv"
    if not csv_path.exists():
        raise FileNotFoundError(
            f"Latent data not found: {csv_path}\n"
            f"Run pipeline_{pipeline}.py first."
        )

    df = pd.read_csv(csv_path)
    X = df.drop(columns=["target"]).values.astype(np.float32)
    y = df["target"].values

    # Subsample for t-SNE speed (preserving class balance)
    if len(X) > max_samples:
        rng = np.random.default_rng(SEED)
        pos_idx = np.where(y == 1)[0]
        neg_idx = np.where(y == 0)[0]

        n_pos = min(len(pos_idx), max_samples // 4)
        n_neg = max_samples - n_pos

        pos_sample = rng.choice(pos_idx, size=n_pos, replace=False)
        neg_sample = rng.choice(neg_idx, size=min(n_neg, len(neg_idx)), replace=False)
        idx = np.concatenate([pos_sample, neg_sample])
        X, y = X[idx], y[idx]
        logger.info(f"  Subsampled to {len(X)} ({n_pos} positive)")

    return X, y


# ---------------------------------------------------------------------------
# Dimensionality reduction
# ---------------------------------------------------------------------------

def run_tsne(X: np.ndarray, seed: int = SEED,
             perplexity: int = 30, n_iter: int = 1000) -> np.ndarray:
    """Run t-SNE on latent representations. Returns 2D embedding."""
    logger.info(f"  Running t-SNE (perplexity={perplexity}, n_iter={n_iter}) "
                f"on shape {X.shape} ...")
    X_scaled = StandardScaler().fit_transform(X)
    emb = TSNE(n_components=2, perplexity=perplexity, max_iter=n_iter,
               random_state=seed, n_jobs=-1).fit_transform(X_scaled)
    return emb


def run_umap(X: np.ndarray, seed: int = SEED) -> np.ndarray:
    """Run UMAP. Returns 2D embedding. Requires umap-learn."""
    try:
        import umap
    except ImportError:
        raise ImportError("umap-learn not installed. Run: pip install umap-learn")
    logger.info(f"  Running UMAP on shape {X.shape} ...")
    X_scaled = StandardScaler().fit_transform(X)
    reducer = umap.UMAP(n_components=2, random_state=seed)
    return reducer.fit_transform(X_scaled)


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def _scatter_2d(emb: np.ndarray, y: np.ndarray,
                title: str, out_path: Path):
    """2D scatter plot colored by class label."""
    fig, ax = plt.subplots(figsize=(7, 6))

    for cls in [0, 1]:
        mask = y == cls
        ax.scatter(
            emb[mask, 0], emb[mask, 1],
            c=CLASS_COLORS[cls], label=CLASS_LABELS[cls],
            s=8, alpha=0.6, linewidths=0, rasterized=True
        )

    pos_pct = 100 * y.mean()
    ax.set_title(f"{title}\n(n={len(y)}, {pos_pct:.1f}% positive)",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("Component 1", fontsize=10)
    ax.set_ylabel("Component 2", fontsize=10)
    ax.legend(title="Class", fontsize=9, title_fontsize=9,
              markerscale=3, framealpha=0.8)
    ax.set_xticks([])
    ax.set_yticks([])

    fig.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close()
    logger.info(f"Saved: {out_path}")


def plot_single(dataset: str, pipeline: str, method: str = "tsne",
                max_samples: int = 5000):
    """t-SNE or UMAP for one dataset x pipeline."""
    logger.info(f"\nVisualization: {dataset} x {pipeline.upper()} [{method.upper()}]")

    X, y = load_latent(dataset, pipeline, max_samples=max_samples)

    if method == "tsne":
        emb = run_tsne(X)
    else:
        emb = run_umap(X)

    title = f"{dataset.upper()} -- {PIPELINE_TITLES.get(pipeline, pipeline.upper())} [{method.upper()}]"
    out = VIZ_DIR / f"repr_{method}_{dataset}_{pipeline}.png"
    _scatter_2d(emb, y, title, out)


def plot_comparison(dataset: str, method: str = "tsne",
                    max_samples: int = 5000):
    """
    Side-by-side 3-panel: D / E / F t-SNE comparison.
    """
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.suptitle(
        f"{dataset.upper()} -- Learned Representations: D (DAE), E (VAE), F (FT-Transformer) "
        f"[{method.upper()}]",
        fontsize=13, fontweight="bold"
    )

    for ax, pl in zip(axes, AI_PIPELINES):
        try:
            X, y = load_latent(dataset, pl, max_samples=max_samples)
        except FileNotFoundError:
            ax.set_title(f"{PIPELINE_TITLES[pl]}\n(data not found)", fontsize=10)
            ax.axis("off")
            continue

        if method == "tsne":
            emb = run_tsne(X)
        else:
            emb = run_umap(X)

        for cls in [0, 1]:
            mask = y == cls
            ax.scatter(emb[mask, 0], emb[mask, 1],
                       c=CLASS_COLORS[cls], label=CLASS_LABELS[cls],
                       s=6, alpha=0.6, linewidths=0, rasterized=True)

        ax.set_title(PIPELINE_TITLES[pl], fontsize=10, fontweight="bold")
        ax.set_xticks([])
        ax.set_yticks([])

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, title="Class", loc="lower center",
               ncol=2, fontsize=10, title_fontsize=10,
               bbox_to_anchor=(0.5, -0.04), markerscale=3)
    fig.tight_layout()

    out = VIZ_DIR / f"repr_comparison_{dataset}_{method}.png"
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    logger.info(f"Comparison plot saved: {out}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="t-SNE/UMAP visualization of learned representations")
    parser.add_argument("--dataset",  default=None, choices=["bank", "retail"])
    parser.add_argument("--pipeline", default=None, choices=AI_PIPELINES)
    parser.add_argument("--method",   default="tsne", choices=["tsne", "umap"])
    parser.add_argument("--max-samples", type=int, default=5000,
                        help="Max samples for t-SNE (default: 5000)")
    args = parser.parse_args()

    datasets  = [args.dataset]  if args.dataset  else ["bank", "retail"]
    pipelines = [args.pipeline] if args.pipeline else AI_PIPELINES

    for ds in datasets:
        for pl in pipelines:
            try:
                plot_single(ds, pl, args.method, args.max_samples)
            except FileNotFoundError as e:
                logger.warning(str(e))

        # Comparison plot (only if all 3 AI pipelines requested)
        if not args.pipeline:
            try:
                plot_comparison(ds, args.method, args.max_samples)
            except Exception as e:
                logger.error(f"Comparison plot failed: {e}")
